"""
export_d1.py — Export local SQLite database to a Cloudflare D1 seed SQL file.

This runs AFTER batch_run.py has populated data/dashboard.db.
It produces data/seed_d1.sql which GitHub Actions feeds to:
  wrangler d1 execute climate_dashboard --file=data/seed_d1.sql --remote

Usage:
  python export_d1.py
  python export_d1.py --db data/dashboard.db --output data/seed_d1.sql
"""

import argparse
import sqlite3
from pathlib import Path
from datetime import datetime, timezone


def export(db_path: str, output_path: str):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append(f"-- D1 seed generated by export_d1.py")
    lines.append(f"-- Source: {db_path}")
    lines.append(f"-- Generated at: {datetime.now(timezone.utc).isoformat()}")
    lines.append("PRAGMA foreign_keys = OFF;")
    lines.append("")

    # ── indicators ───────────────────────────────────────────────────────
    rows = conn.execute("SELECT * FROM indicators ORDER BY id").fetchall()
    if rows:
        lines.append("-- ── indicators ──────────────────────────────────────────────")
        lines.append("DELETE FROM indicators;")
        for r in rows:
            lines.append(
                "INSERT INTO indicators "
                "(id, name, module, tier, data_type, unit, source_type, "
                "valid_range_min, valid_range_max) VALUES "
                f"({_q(r['id'])}, {_q(r['name'])}, {_q(r['module'])}, "
                f"{_q(r['tier'])}, {_q(r['data_type'])}, {_q(r['unit'])}, "
                f"{_q(r['source_type'])}, {_n(r['valid_range_min'])}, "
                f"{_n(r['valid_range_max'])});"
            )
        lines.append("")

    # ── country_data ─────────────────────────────────────────────────────
    rows = conn.execute(
        "SELECT * FROM country_data ORDER BY country_iso3, year, indicator_id"
    ).fetchall()

    if rows:
        lines.append("-- ── country_data ────────────────────────────────────────────")
        lines.append("DELETE FROM country_data;")
        # Batch into chunks to avoid hitting D1's 10 MB statement limit
        CHUNK = 500
        for i in range(0, len(rows), CHUNK):
            chunk = rows[i:i + CHUNK]
            values_list = []
            for r in chunk:
                values_list.append(
                    f"({_q(r['country_iso3'])}, {_q(r['indicator_id'])}, "
                    f"{r['year']}, {_n(r['value'])}, "
                    f"{_q(r['unit'])}, {_q(r['source'])}, "
                    f"{r['is_estimated'] or 0}, "
                    f"{_q(r['submission_date'])}, {_q(r['round_id'])}, "
                    f"{_q(r['region_id'])}, {_q(r['nace_node_id'])}, "
                    f"{_q(r['currency'])}, {_n(r['fx_rate_to_eur'])}, "
                    f"{_q(r['fx_rate_date'])}, "
                    f"{_n(r['physical_risk'])}, {_n(r['transition_risk'])}, "
                    f"{_n(r['financial_vulnerability'])}, {_n(r['ccr_score'])}, "
                    f"{_n(r['ranking_position'])})"
                )
            lines.append(
                "INSERT INTO country_data "
                "(country_iso3, indicator_id, year, value, unit, source, "
                "is_estimated, submission_date, round_id, "
                "region_id, nace_node_id, "
                "currency, fx_rate_to_eur, fx_rate_date, "
                "physical_risk, transition_risk, financial_vulnerability, "
                "ccr_score, ranking_position) VALUES"
            )
            lines.append(",\n".join(values_list) + ";")
        lines.append("")

    # ── submissions_log ───────────────────────────────────────────────────
    rows = conn.execute(
        "SELECT * FROM submissions_log ORDER BY submission_date"
    ).fetchall()

    if rows:
        lines.append("-- ── submissions_log ─────────────────────────────────────────")
        lines.append("DELETE FROM submissions_log;")
        for r in rows:
            lines.append(
                "INSERT INTO submissions_log "
                "(country_iso3, analyst_name, submission_date, round_id, "
                "national_records, regional_records, sectoral_records, "
                "validation_status, error_count, warning_count, notes) VALUES "
                f"({_q(r['country_iso3'])}, {_q(r['analyst_name'])}, "
                f"{_q(r['submission_date'])}, {_q(r['round_id'])}, "
                f"{r['national_records'] or 0}, {r['regional_records'] or 0}, "
                f"{r['sectoral_records'] or 0}, "
                f"{_q(r['validation_status'])}, "
                f"{r['error_count'] or 0}, {r['warning_count'] or 0}, "
                f"{_q(r['notes'])});"
            )

    conn.close()

    sql = "\n".join(lines) + "\n"
    Path(output_path).write_text(sql, encoding='utf-8')

    total_rows = sql.count("INSERT INTO")
    print(f"✓ Exported {total_rows} INSERT statements → {output_path}")
    print(f"  File size: {Path(output_path).stat().st_size / 1024:.1f} KB")


# ── SQL quoting helpers ───────────────────────────────────────────────────

def _q(val) -> str:
    """Quote a string value for SQL, or return NULL."""
    if val is None:
        return "NULL"
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def _n(val) -> str:
    """Format a numeric value, or return NULL."""
    if val is None:
        return "NULL"
    return str(val)


# ─────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Export SQLite → Cloudflare D1 seed SQL"
    )
    parser.add_argument('--db',     default='data/dashboard.db',
                        help='SQLite database path')
    parser.add_argument('--output', default='data/seed_d1.sql',
                        help='Output SQL file path')
    args = parser.parse_args()

    if not Path(args.db).exists():
        print(f"Error: database not found: {args.db}")
        raise SystemExit(1)

    export(args.db, args.output)


if __name__ == '__main__':
    main()
